server:
  port: 2228

spring:
  application:
    name: web-service

uri:
  input: http://localhost:2227/api/v1/data/input
  analysis: http://localhost:2227/api/v1/data/analysis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:2229/eureka