spring:
  config:
    import: optional:configserver:http://localhost:2231
  application:
    name: web-service

uri:
  input: http://localhost:2230/query-service/api/v1/data/input
  analysis: http://localhost:2230/query-service/api/v1/data/analysis
