spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:2231
  rabbitmq:
    host: localhost
    username: ${POSTGRE_USER}
    password: ${POSTGRE_PASS}
    port: 5672
    virtual-host: /
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: web-data-producer
          uri: lb://web-data-producer
          predicates:
            - Path=/api/v1/data
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie

        - id: web-service
          uri: lb://web-service
          predicates:
            - Path=/api/v1/data/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
management:
  endpoints:
    web:
      exposure:
        include: "beans,configprops,env,health,httptrace,info"
