server:
  port: ${PORT:0}

spring:
  application:
    name: elastic-kafka-service
  kafka:
    consumer:
      bootstrap-servers: 127.0.0.1:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:2229/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

kafka:
  topics:
    data: rawData
  keys:
    data: data
  groups:
    data: elastic_data_group_1

elasticsearch:
  port: localhost:9200
