spring:
  application:
    name: query-service
  config:
    import: optional:configserver:http://localhost:2231
  rabbitmq:
    host: localhost
    port: 5672
    username: ${POSTGRE_USER}
    password: ${POSTGRE_PASS}
    virtual-host: /
  datasource:
    url: jdbc:postgresql://localhost:3344/analysis_db
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
    jpa:
      generate-ddl: false
      show-sql: true
      hibernate:
        ddl-auto: none

elasticsearch:
  port: localhost:9200