server:
  port: 2226

spring:
  application:
    name: analytics-service
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.xml
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:3344/analysis_db
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  kafka:
    consumer:
      bootstrap-servers: 127.0.0.1:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:2229/eureka

kafka:
  topics:
    data: rawData
  keys:
    data: data
  groups:
    data: analysis_data_group