server:
  port: 2231

spring:
  application:
    name: config-server
  profiles:
    active: git
  rabbitmq:
    host: localhost
    username: ${POSTGRE_USER}
    password: ${POSTGRE_PASS}
    port: 5672
    virtual-host: /
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dasWarder/analyzerConfig
          username: ${GIT_USER}
          password: ${GITHUB_ACCESS_TOKEN}
          default-label: main

management:
  endpoints:
    web:
      exposure:
        include:
          - busrefresh
